name:                Game2048
version:             0.1.0.0
github:              "githubuser/Game2048"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Game2048#readme>

dependencies:
- base >= 4.7 && < 5
- random  >= 1.1 && < 2
- brick
- linear >= 1.20.6 && < 1.21
- containers 
- vty

library:
  source-dirs: src

executables:
  Game2048-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game2048
    - base >= 4.7 && < 5
    - random >= 1.1 && < 2
    - brick
    - vty
    - linear >= 1.20.6 && < 1.21
    - containers

tests:
  Game2048-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Game2048
    - base >= 4.7 && < 5
    - random >= 1.1 && < 2
    - brick
    - vty
    - linear >= 1.20.6 && < 1.21
    - containers 	
